<a href="https://colab.research.google.com/github/RitulMohan/TF.Autoencoder/blob/main/tensorfloww_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSORFLOW INRODUCTION 
 

In [ ]:
import tensorflow as tf

In [ ]:
string = tf.Variable("Bhay ye toh string hai" , tf.string)
number = tf.Variable(324, tf.int32) 
floating = tf.Variable(1.2345, tf.float32)

print(string)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Bhay ye toh string hai'>


In [ ]:
rank1_tensor = tf.Variable(["BRUH"], tf.string)
rank2_tensor = tf.Variable([["Bruh","whatever"], ["OK","idc"]], tf.string)
tf.rank(rank1_tensor)
tf.rank(rank2_tensor)
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
rank2_tensor.shape

TensorShape([2, 2])

CHANGING SHAPES 

In [ ]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1, [3,2,1])
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]], shape=(3, 2, 1), dtype=float32)


-1 tells the tensor to calculate the size of the dimension in that place

this will reshape the tensor to [3,2]

The numer of elements in the reshaped tensor MUST match the number in the original

In [ ]:
tensor3 = tf.reshape(tensor1, [3,-1])
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


# SLICING tensors 🤺 

In [ ]:
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]
tensor = tf.Variable(matrix,tf.int32)
print(tensor)
print(tf.rank(tensor))
print(tf.shape(tensor))   #alternately you can use tensor.shape

<tf.Variable 'Variable:0' shape=(4, 5) dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int32)>
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([4 5], shape=(2,), dtype=int32)


In [ ]:
#select the 3rd element
three = tensor[0,2]
print(three)

#select the 2nd row
second = tensor[1]
print(second)

#select the 3rd column 
third = tensor[:, 2]
print(third)

#select 2 rows at the same time 
rows_2 = tensor[1::3]
print(rows_2)


column_1_in_row_2_and_3 = tensor[0:4, 0]
print(column_1_in_row_2_and_3)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([ 6  7  8  9 10], shape=(5,), dtype=int32)
tf.Tensor([ 3  8 13 18], shape=(4,), dtype=int32)
tf.Tensor([[ 6  7  8  9 10]], shape=(1, 5), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
